language: node_js
node_js:
  - 8
install:
  - "yarn install -g"
script:
  - "make clean"
  - "make"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
branches:
  only:
    - gh-pages
    - /.*/
