[project]
site_name = "AMWA NMOS Interface Specification Template"
site_description = "Template for AMWA NMOS Interface Specifications"
site_url = "https://specs.amwa.tv/is-template/"
repo_name = "AMWA-TV/is-template"
repo_url = "https://github.com/AMWA-TV/is-template"
extra_css = ["stylesheets/extra.css"]
extra_javascript = ["javascripts/json-viewer.js"]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
permalink = false

[project.extra.version]
provider = "mike"
