[project]
site_name = "AMWA NMOS Interface Specification Template"
site_description = "Template for AMWA NMOS Interface Specifications"
site_url = "https://specs.amwa.tv/is-template/"
repo_name = "AMWA-TV/is-template"
repo_url = "https://github.com/AMWA-TV/is-template"

[project.extra.version]
provider = "mike"
