name: Render
on:
  push:
    branches:
        - 'v[0-9]*.[0-9]*'
        - 'publish-*'
    tags:
        - 'v[0-9]*.[0-9]*'
  release:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Bundler
        run: gem install bundler
      - name: Setup 
        run: make distclean build-tools
      - name: Build
        run: make build
      - name: Remove source-repo
        run: rm -rf source-repo/
      - name: Make site
        run: make site
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Can we see _site
        run: ls
