name: Render
on:
  workflow_dispatch:

  push:
    branches:
        - 'v[0-9]+.[0-9]+-dev'
        - 'v[0-9]+.[0-9]+.x'
        - 'publish-*'
    tags:
        - 'v[0-9]+.[0-9]+'
        - 'v[0-9]+.[0-9]+.[0-9]+'
  release:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Use NMOS Render
        uses: docker://peterbrightwell/nmos-render:latest